[project]
name = "desafio-a2a-mcp"
version = "0.1.0"
description = "Desafio A2A com MCP - MBA Engenharia de Software com IA"
requires-python = ">=3.10"
dependencies = [
    "mcp==2.2.0",
    "fastapi==0.141.1",
    "uvicorn==0.54.0",
    "httpx==0.28.1",
    "python-dotenv==1.2.3",
    "pydantic==2.13.5"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["start_mcp", "start_agente"]

